config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :url_shorteners

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url_shortener.rb
class UrlShortener < ApplicationRecord
    validates :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_shorteners_controller.rb
class UrlShortenersController < ApplicationController
    def index
        @url_shorteners = UrlShortener.all
    end
    
    def show
        @url_shortener = UrlShortener.find(params[:id])
    end

    def edit
        @url_shortener = UrlShortener.find(params[:id])
    end

    def new
        @url_shortener = UrlShortener
        .new
    end

    def create
        @url_shortener = UrlShortener.new(url_shortener_params)
        @url_shortener.short = UrlShortener.count.to_s(36)
 
        if @url_shortener.save
            redirect_to @url_shortener
        else
            render 'new'
        end
    end

    def update
        @url_shortener = UrlShortener.find(params[:id])
       
        if @url_shortener.update(url_shortener_params)
          redirect_to @url_shortener
        else
          render 'edit'
        end
    end


    def destroy
        @url_shortener = UrlShortener.find(params[:id])
        @url_shortener.destroy
    
        redirect_to url_shorteners_path
    end

    private
        def url_shortener_params
            params.require(:url_shortener).permit(:url)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_shorteners_helper.rb
module UrlShortenersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitlyLike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/url_shorteners/_form.html.erb
<%= form_with(model: @url_shortener, local: true) do |form| %>
 
  <% if @url_shortener.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@url_shortener.errors.count, "error") %> prohibited
        this URL from being saved:
      </h2>
      <ul>
        <% @url_shortener.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/url_shorteners/edit.html.erb
<h1>Edit URL</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', url_shorteners_path %>

app/views/url_shorteners/index.html.erb
<h1>Listing articles</h1>
 
<%= link_to 'New short URL', new_url_shortener_path %>

<table>
  <tr>
    <th>URL</th>
    <th>Short URL</th>
    <th></th>
  </tr>
 
  <% @url_shorteners.each do |url_shortener| %>
    <tr>
      <td><%= url_shortener.url %></td>
      <td><a href="<%= url_shortener.url %>">localhost:3000/<%= url_shortener.short %></a></td>
      <td><%= link_to 'Show', url_shortener_path(url_shortener) %></td>
      <td><%= link_to 'Edit', edit_url_shortener_path(url_shortener) %></td>
      <td><%= link_to 'Destroy', url_shortener_path(url_shortener), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/url_shorteners/new.html.erb
<h1>New Url</h1>

<%= form_with scope: :url_shortener, url: url_shorteners_path, local: true do |form| %>
    <% if @url_shortener.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@url_shortener.errors.count, "error") %> prohibited
          this URL from being saved:
        </h2>
        <ul>
          <% @url_shortener.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <p>
      <%= form.label :url %><br>
      <%= form.text_field :url %>
    </p>
   
    <p>
      <%= form.submit %>
    </p>
  <% end %>

  <%= link_to 'Back', url_shorteners_path %>

app/views/url_shorteners/show.html.erb
<p>
  <strong>URL:</strong>
  <%= @url_shortener.url %>
</p>
 
<p>
  <strong>short URL:</strong>
  <%= @url_shortener.short %>
</p>

<%= link_to 'Edit', edit_url_shortener_path(@url_shortener) %>
<%= link_to 'Back', url_shorteners_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My URLs', controller: 'url_shorteners' %>